Add Appearances page and added Appearance button in navbar to redirect to Appearances Page
aslams2020/Stark-Tech-Portfolio pull request #118
Opened 2024-10-03 13:50 UTC by Tamanna225

Issue: #24

**Features Added:** Created a new Page of Appearances of Tony Stark(Added Appearances.html and Appearances.css)
**Changes Made:** Added the Appearances Button navbar to redirect to Appearances page
**Responsiveness:** Responsive for All the screens
All the other features same as index.html

**Mobile View:**

![Screenshot 2024-10-03 191443](https://github.com/user-attachments/assets/55914266-ef21-4120-9f3b-2a8184dfd1d1)

**Laptop View**

![Screenshot 2024-10-03 191512](https://github.com/user-attachments/assets/6018bca5-ac9f-421f-ae58-f0a94653eea5)

If any further changes required Let me know

2024-10-03 14:25 UTC, aslams2020 commented on Appearances.css
> +.logo img {
Please see that the main logo of the website is reduced in size.

Original : 
![image](https://github.com/user-attachments/assets/571131d8-e75b-42b3-afa1-1a0f8dd9e734)

After your changes - 
![image](https://github.com/user-attachments/assets/04a4b364-55bb-4ae6-a8f2-a624dc3fd366)

2024-10-03 14:31 UTC, aslams2020 requested changes
The changes In Summary you have to make - 

1. See the Main-logo in Navbar. **Get it's size back to normal.**
2. Replace the **"Merchandise"** Link with **"Appearances" link**.. Instead of Newly creating a link in navbar.
3. In Appearances Page : **Change the Colour Of the Main Heading**. It is not following the web theme.
![image](https://github.com/user-attachments/assets/c02f9979-e0b9-4e60-9d74-ef79502612da)

2024-10-03 14:53 UTC, Tamanna225 commented
Made the required changes

2024-10-03 15:34 UTC, aslams2020 approved these changes
Approved

2024-10-03 15:39 UTC, merged

2024-10-25 19:03 UTC, aslams2020 commented
@Tamanna225 Hi, 
I got My account back today. On next leaderboard update you'll be able to see your points. 
Sorry for the inconvenience. Keep contributing.🚀